version: "3"
services:
  ddl-postgres:
    image: postgres:alpine
    container_name: ddl-postgres
    restart: always
    volumes:
      - ~/data/ddl-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ddl
      - POSTGRES_USER=ddlu
      - POSTGRES_PASSWORD=ddlp
  ddl-redis:
    image: redis:alpine
    container_name: ddl-redis
    volumes:
      - ~/data/ddl-redis:/data
    restart: always
  ddl-rabbitmq:
    image: rabbitmq
    container_name: ddl-rabbitmq
    restart: always
    hostname: my-rabbit
    ports:
      - '0.0.0.0:5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/data/ddl-rabbitmq:/var/lib/rabbitmq
  ddl-backend:
    command: bash /app/docker/entrypoint.sh
    volumes:
      - ~/data/ddl-backend:/data
    image: 4ddl/ddlb
    container_name: ddl-backend
    restart: always
    depends_on:
      - ddl-redis
      - ddl-postgres
      - ddl-rabbitmq
    environment:
      - REDIS_HOST=ddl-redis
      - POSTGRES_HOST=ddl-postgres
      - POSTGRES_DB=ddl
      - POSTGRES_USER=ddlu
      - POSTGRES_PASS=ddlp
      - RABBITMQ_HOST=ddl-rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DDL_ENV=production
      - EMAIL_ENABLE=True
      - EMAIL_HOST=sample.com
      - EMAIL_HOST_USER=user@sample.com
      - EMAIL_HOST_PASSWORD=password
      - SECRET_KEY=secret_key
      - JUDGE_TOKEN=judge_token
  ddl-web:
    image: 4ddl/ddlf
    container_name: ddl-web
    depends_on:
      - ddl-backend
    restart: always
    environment:
      - BACKEND_HOST=ddl-backend
      - BACKEND_PORT=8000
    ports:
      - '0.0.0.0:80:80'

