version: "3"
services:
  oj-consumer:
    command: celery -A tasks worker -l info -Q judge
    volumes:
      - ~/data/oj-backend/test_cases:/judge/test_cases
    image: wustacm/oj-consumer
    container_name: oj-consumer
    restart: always
    environment:
      - BACKEND_URL=http://127.0.0.1
      - BROKER_URL=amqp://guest:guest@127.0.0.1:5672/
      - OJ_DEBUG=True
      - OJ_SYNC_ENABLE=True
